<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class BillTableCreation extends Migration
{
    public function up()
    {
        // Define the bills table
        $this->forge->addField([
            'id'          => [
                'type'           => 'INT',
                'unsigned'      => true,
                'auto_increment' => true
            ],
            'apartment_id' => [
                'type'       => 'INT',
                'unsigned'  => true,
            ],
            'tenant_id' => [
                'type'       => 'INT',
                'unsigned'  => true,
                'null'       => true,
            ],
            'amount' => [
                'type'       => 'DECIMAL',
                'constraint' => '10,2',
            ],
            'issued_date' => [
                'type' => 'DATE',
            ],
            'due_date' => [
                'type' => 'DATE',
            ],
            'generated_by' => [
                'type'       => 'INT',
                'unsigned'  => true,
                'null'       => false,  // This can be null if the bill is not generated by anyone specific
            ],
            'generated_at' => [
                'type'       => 'DATETIME',
                'null'       => false,  
            ],
            'paid' => [
                'type'    => 'TINYINT',
                'constraint' => '1',
                'default' => 0, // Unpaid by default
            ],
            'paid_by' => [
                'type'    => 'ENUM',
                'constraint' => "'owner','tenant'",
                'default' => 'owner', // Default: owner pays
            ],
            'paid_at' => [
                'type'       => 'DATETIME',
                'null'       => true,  // This can be null if the bill hasn't been paid yet
            ],
        ]);

        // Add primary key
        $this->forge->addPrimaryKey('id');

        // Add foreign keys
        $this->forge->addForeignKey('apartment_id', 'apartments', 'id', 'CASCADE', 'CASCADE');
        $this->forge->addForeignKey('tenant_id', 'tenants', 'id', 'SET NULL', 'CASCADE');
        //$this->forge->addForeignKey('generated_by', 'users', 'id', 'SET NULL', 'CASCADE');

        // Create the table
        $this->forge->createTable('bills');
    }

    public function down()
    {
        // Drop the bills table
        $this->forge->dropTable('bills');
    }
}
